name: Release linctl

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g., v1.0.0)'
        required: true
        type: string
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache-dependency-path: go.sum

      - name: Download dependencies
        run: |
          go mod download
          go mod verify

      - name: Build multi-platform binaries
        run: |
          mkdir -p dist

          # Build for linux/amd64
          GOOS=linux GOARCH=amd64 go build \
            -ldflags="-s -w -X main.version=${{ github.ref_name }}" \
            -o dist/linctl-linux-amd64 .

          # Build for linux/arm64
          GOOS=linux GOARCH=arm64 go build \
            -ldflags="-s -w -X main.version=${{ github.ref_name }}" \
            -o dist/linctl-linux-arm64 .

      - name: Generate checksums
        run: |
          cd dist
          sha256sum * > checksums.txt
          cat checksums.txt

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/linctl-linux-amd64
            dist/linctl-linux-arm64
            dist/checksums.txt
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}